const projectData = [
  {
    id: 1,
    image: '../img/oldagram-square.png',
    name: 'Oldagram',
    intro: 'Oldagram is a small clone of Instagram, designed with a similar layout and functionality. The project utilizes JavaScript and DOM manipulation to create an interactive user interface.',
    description: 'It showcases a collection of posts, each consisting of a user"s name, username, location, avatar, post image, comment, and number of likes. The likes count is displayed dynamically, and users can increment the likes by clicking on the "increment" button or the heart icon. The project leverages event listeners to update the likes count and reflect the changes in real-time.', 
    techStack: 'JavaScript, DOM manipulation, HTML, CSS.',
    liveLink: 'https://oldogram.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/Oldagram',
  },
  {
    id: 2,
    image: '../img/tenzies.jpg',
    name: 'Tenzies',
    intro: 'Tenzies is a dice game built using React. The objective of the game is to roll the dice until all of them show the same value.',
    description: 'The game features a dynamic user interface with dice that can be held or released to freeze their current value between rolls. The game tracks the number of rolls taken and displays the best score achieved so far, as well as the last score. Users have the option to clear the stored scores. The game also includes a visual effect of confetti when the player achieves "tenzies" (all dice showing the same value)', 
    techStack: 'React, React hooks, nanoid, react-confetti',
    liveLink: 'https://sweet-belekoy-83486a.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/Tenzies_Game',
  },
  {
    id: 3,
    image: '../img/password-generator.jpg',
    name: 'Password Generator',
    intro: 'The Password Generator is a JavaScript-based tool that generates random passwords. It utilizes an array of characters containing uppercase and lowercase letters, numbers, and special symbols.',
    description: 'The tool allows users to generate two random passwords simultaneously, which are displayed in separate boxes on the webpage. Each password consists of 15 characters randomly selected from the available character set. The generated passwords can be used for various purposes, such as creating strong and secure passwords for online accounts.', 
    techStack: ' JavaScript, HTML, CSS.',
    liveLink: 'https://sage-kleicha-673556.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/Random_Password_Generator_2',
  },
  {
    id: 4,
    image: '../img/meme-generator.jpg',
    name: 'Meme Generator',
    intro: 'The Meme Generator is a React-based application that allows users to generate custom memes by adding text to a random image fetched from an API.',
    description: 'The application features two input fields for entering the top and bottom text of the meme. By clicking the "Get a new Meme Image" button, a random image is fetched from the Imgflip API and displayed alongside the entered text. Users can update the text inputs and generate new meme combinations by clicking the button again. The generated memes can be humorous, satirical, or creative, depending on the user"s input.', 
    techStack: ' React, JavaScript, HTML, CSS, Imgflip API',
    liveLink: 'https://vermillion-souffle-8b93ed.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/Meme-Generator',
  },
  {
    id: 5,
    image: '../img/meme-generator.jpg',
    name: 'Personal Dashboard',
    intro: 'The Personal Dashboard is a web application that provides a personalized dashboard experience to users. The application uses the Fetch API to make API requests and handle the responses asynchronously.',
    description: 'It fetches data from Unsplash API, CoinGecko API, OpenWeatherMap API, Geolocation API to display dynamic content such as a random nature image from Unsplash as the background, the author of the image, real-time cryptocurrency data (specifically for Dogecoin), the current time, and the weather information based on the user"s geolocation.  It also handles errors gracefully and provides default data or fallbacks in case of any issues with the API requests', 
    techStack: 'JavaScript, HTML, CSS, Fetch API',
    liveLink: 'https://fluffy-clafoutis-cf081f.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/dashboard',
  },
  {
    id: 6,
    image: '../img/meme-generator.jpg',
    name: 'AirBnB Experiences',
    intro: 'The Personal DashboarThe AirBnB Experiences with React is a web application that showcases a list of experiences using React components.',
    description: 'The application imports components such as Navbar, Hero, and Card from separate files to create a modular structure. It also imports an array of data containing information about the experiences from a local file. The data array is then mapped over to generate Card components dynamically for each experience. Each Card component represents an individual experience, displaying relevant details such as images, descriptions, and ratings.', 
    techStack: 'React, JavaScript, HTML, CSS',
    liveLink: 'https://rococo-licorice-cc2ee5.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/AirBnB-experiences-with-React',
  },
  {
    id: 7,
    image: '../img/color-picker.jpg',
    name: 'Color Scheme Generator',
    intro: 'The Color Scheme Generator is a web application that generates a color scheme based on a user-selected color and scheme type. ',
    description: ' The application uses an HTML form with a color picker and scheme selection dropdown. unction retrieves the user-selected color and scheme type from the form inputs. It then makes a GET request to thecolorapi.com, passing the selected color and scheme type as parameters. The API returns a set of colors that match the provided scheme type, based on the selected color. The returned colors are stored in an array, and the function loops over each color to generate HTML elements dynamically. Each color is displayed as a colored shape with its corresponding hexadecimal value.', 
    techStack: 'JavaScript, HTML, CSS, Fetch API, thecolorapi.com API.',
    liveLink: 'https://rainbow-biscuit-c760c0.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/Color-Scheme-Generator',
  },
  {
    id: 8,
    image: '../img/restaurant-menu.jpg',
    name: 'Food Ordering Site',
    intro: 'The Food Ordering Site is an online platform that allows users to browse and order various food items. Users can view the menu, add items to their order, and complete the checkout process. The site provides a user-friendly interface to select food items, track the order, and make payments. ',
    description: ' The Food Ordering Site offers a diverse menu of delicious food items. Users can add items to their order with the ability to increase or decrease quantities. The site dynamically updates the order total and displays the selected items for review. Upon completing the order, users receive a confirmation message with the estimated delivery time.', 
    techStack: 'JavaScript, HTML, CSS, Fetch API, event listeners, DOM manipulation',
    liveLink: 'https://order-food-items.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/Food-Ordering-Site',
  },
  {
    id: 9,
    image: '../img/twitter.jpg',
    name: 'Twitter Frontend Clone',
    intro: 'The Twitter Frontend Clone is a web application that replicates the user interface and functionality of Twitter. Users can view a feed of tweets, interact with them by liking, retweeting, and replying, as well as post their own tweets.',
    description: 'The Twitter Frontend Clone offers a seamless experience of browsing tweets and engaging with the content. Users can like tweets, retweet them, and view replies. The clone also enables users to compose and post their own tweets, contributing to the interactive and dynamic nature of the platform. The clone provides a familiar and intuitive interface that resembles the core features of Twitter', 
    techStack: 'JavaScript, HTML, CSS, Fetch API, uuid ',
    liveLink: 'https://helpful-panda-1d5db6.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/twitter_clone',
  },
  {
    id: 10,
    image: '../img/tagurl.png',
    name: 'TagURL - Browser Extension',
    intro: 'The TagURL project allows users to save and organize their favorite website URLs along with associated tags. It provides a simple interface to save URLs, add tags, and remove saved entries. Users can also delete all saved data at once.',
    description: 'The project is built as a browser extension using HTML, CSS, and JavaScript. It leverages the Chrome Extension API (chrome.tabs.query) to capture the active tab"s URL and the user"s input for the associated tag. The saved URL and tag are stored as an object in the myLeads array, which is then stored in the browser"s local storage using localStorage.setItem(). The saved entries are rendered on the page, displaying the URL, tag, and a remove button for each entry. Users can remove individual entries by clicking the "Remove" button, which updates the myLeads array and local storage accordingly. Additionally, users can delete all saved data by double-clicking the "Delete All" button.', 
    techStack: 'JavaScript, HTML, CSS, Chrome Extension API',
    liveLink: 'https://helpful-panda-1d5db6.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/TagURL',
  },
  {
    id: 11,
    image: '../img/movie_watchlist.jpg',
    name: 'Movie Watchlist',
    intro: 'This Movie Watchlist project allows users to search for movies using the Open Movie Database (OMDb) API and add them to their watchlist. It provides information about the movies such as title, poster, IMDb rating, runtime, genre, and plot. Users can add movies to their watchlist and remove them if desired.',
    description: 'The project is built using HTML, CSS, and JavaScript. It utilizes the OMDb API to fetch movie data based on user search input. The fetched movie data is then stored in the moviesArray and rendered on the page. The user can add movies to their watchlist by clicking the "Add to Watchlist" button, and the movie is stored in the watchlistArray and in the browser"s local storage. If a movie is already in the watchlist, the user is alerted with a message. The user can also remove movies from the watchlist by clicking the "Remove from Watchlist" button, which updates the watchlistArray and local storage accordingly.', 
    techStack: 'JavaScript, HTML, CSS, OMDb API API ',
    liveLink: 'https://remarkable-7d47ea.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/Movie_Watchlist',
  },
  {
    id: 12,
    image: '../img/learning_journal.jpg',
    name: 'Learning Journal',
    intro: 'portfolio styled journal replete with blogs and portfolio',
    description: ' The HTML structure consists of a head section containing the document title, CSS stylesheets, and fonts. The body section includes a header with a navigation menu, a featured article with an image, title, and content, and a main section with recent articles displayed in a container. The main section also includes a sidebar with widgets displaying information about the author and projects. Finally, a footer is present at the bottom of the page with copyright information.', 
    techStack: ' HTML, CSS,  Google Fonts (Quicksand), static web pages.',
    liveLink: 'https://learning-journal-aside.netlify.app/',
    githubLink: 'https://github.com/kamlesh-21/my-learning-journal',
  },
];

export default projectData;